name: Run Unit Tests

on:
  pull_request:
    branches: [ "dev" ]   # <--- Ändrat till 'pull_request' mot 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x' # Behåll denna om ni kör .NET 9, annars byt till '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run unit tests
      run: dotnet test --no-build --verbosity normal